---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - templates/server/networkpolicy.yml
  - templates/server/service.yml
  - templates/server/deployment.yml
  - templates/server/certificate.yml
  - templates/server/servicemonitor.yml
  - templates/server/ingressroute.yml
  - templates/machinelearning/networkpolicy.yml
  - templates/machinelearning/service.yml
  - templates/machinelearning/deployment.yml
  - templates/postgres/networkpolicy.yml
  - templates/postgres/service.yml
  - templates/postgres/statefulset.yml
  - templates/redis/networkpolicy.yml
  - templates/redis/service.yml
  - templates/redis/statefulset.yml

secretGenerator:
  - name: immich-config
    literals:
      - DB_HOSTNAME=postgres.immich.svc
      - DB_USERNAME=immich
      - DB_PASSWORD=changeme
      - DB_DATABASE_NAME=immich
      - IMMICH_HOST=0.0.0.0
      - IMMICH_PORT=3003
      - IMMICH_MEDIA_LOCATION=/data/Immich
      - IMMICH_TELEMETRY_INCLUDE=all
      - IMMICH_TELEMETRY_EXCLUDE=host
      - IMMICH_API_METRICS_PORT=8081
      - IMMICH_MICROSERVICES_METRICS_PORT=8082
      - REDIS_HOSTNAME=redis.immich.svc
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=changeme
      - SERVER_PORT=3001
      - TZ=Europe/Prague
      - LOG_LEVEL=verbose
      - UPLOAD_LOCATION=/data/Immich/upload
  - name: postgres-config
    literals:
      - POSTGRES_DB=immich
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/var/lib/postgresql/data/pgdata

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf=files/redis.conf
      - redis.acl=files/redis.acl

generatorOptions:
  disableNameSuffixHash: true
