---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: server

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: immich
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 3003
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: immich

spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: immich
  ports:
    - name: http
      port: 3003
    - name: metrics-api
      port: 8081
    - name: metrics-micro
      port: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server

spec:
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/part-of: immich
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1066
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - {key: app.kubernetes.io/name, operator: In, values: [server]}
                    - {key: app.kubernetes.io/part-of, operator: In, values: [immich]}
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v1.109.2
          resources:
            limits:
              gpu.intel.com/i915: "1"
            requests:
              cpu: 10m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 3003
            - name: metrics-api
              containerPort: 8081
            - name: metrics-micro
              containerPort: 8082
          envFrom:
            - secretRef:
                name: immich-config
          volumeMounts:
            - name: data
              mountPath: /data # /usr/src/app/upload
      volumes:
        - name: data
          nfs:
            server: "192.168.1.100"
            path: /mnt/pictures

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich

spec:
  commonName: fotos.home.arpa
  dnsNames:
    - fotos.home.arpa
  secretName: immich-certificate
  issuerRef:
    name: trusted-ca
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  annotations:
    link.argocd.argoproj.io/external-link: https://fotos.home.arpa

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`fotos.home.arpa`)
      kind: Rule
      services:
        - name: server
          port: 3003
  tls:
    secretName: immich-certificate

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: immich
  endpoints:
    - port: metrics-api
    - port: metrics-micro
