---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres

spec:
  replicas: 1
  serviceName: postgres-hl
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: immich
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: postgres-init
          image: tensorchord/pgvecto-rs:pg16-v0.3.0
          command:
            - docker-enforce-initdb.sh
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
          envFrom:
            - secretRef:
                name: postgres-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: shm
              mountPath: /dev/shm
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg16-v0.3.0
          command:
            - postgres
          args:
            - -c
            - shared_preload_libraries=vectors.so
            - -c
            - 'search_path="$$user", public, vectors'
            - -c
            - max_wal_size=2GB
            - -c
            - logging_collector=on
            - -c
            - wal_compression=on
            - -c
            - shared_buffers=512MB
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
          ports:
            - name: postgres
              containerPort: 5432
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            tcpSocket:
              port: 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
          envFrom:
            - secretRef:
                name: postgres-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 4Gi

# kubectl exec -it -n immich postgres-0 -- bash -c 'pg_dumpall -p 5432 -U foobar' > backup
# kubectl cp -n immich backup postgres-0:/var/lib/postgresql/backup
# kubectl exec -it -n immich postgres-0 -- bash -c 'psql -p 5432 -U foobar -d nyancat -f /var/lib/postgresql/backup'
